### ISSUE TITLE
How to get extract tidal constants with OTIS format tidal solutions

### ISSUE THREAD

**Issue by tonystevenj** [tsutterley/pyTMD#26]
Hi, sorry to bother, I'm new in this area and found this library amazing, I'm figuring out how to use it.

I'm trying to extract tidal constants with this function in PyTMD： extract_tidal_constants.

I downloaded the OTIS format tidal solutions there: http://people.oregonstate.edu/~erofeevs/

The specific data used is "East Coast of America 1/30º"

Code as follows:

```
from pyTMD import read_tide_model

grid_file = "F:/Z-Main Affairs(USA)/US Stusy/PyTMD/historical data/EC/DATA/grid_EC"
model_file = "F:/Z-Main Affairs(USA)/US Stusy/PyTMD/historical data/EC/DATA/Model_EC"
EPSG = "4326"
ilon = "-73.935242"
ilat = "40.730610"
amp,ph,D,c = read_tide_model.extract_tidal_constants(ilon, ilat, grid_file, model_file, EPSG,
                             TYPE=type, METHOD='spline', GRID='OTPS')
print("amp: ",amp)
print("ph: ",ph)
print("D: ",D)
print("c: ",c)
```

Console error info:
```
C:\Users\tonys\Anaconda3\envs\Tide_scratch2\lib\site-packages\pyTMD\read_tide_model.py:596: RuntimeWarning: overflow encountered in long_scalars
  constituents = [c.decode("utf-8").rstrip() for c in fid.read(nc*4).split()]
Traceback (most recent call last):
  File "F:/pycharm-workspace/Tide_scratch/main.py", line 21, in <module>
    TYPE=type, METHOD='spline', GRID='OTPS')
  File "C:\Users\tonys\Anaconda3\envs\Tide_scratch2\lib\site-packages\pyTMD\read_tide_model.py", line 223, in extract_tidal_constants
    constituents,nc = read_constituents(model_file)
  File "C:\Users\tonys\Anaconda3\envs\Tide_scratch2\lib\site-packages\pyTMD\read_tide_model.py", line 596, in read_constituents
    constituents = [c.decode("utf-8").rstrip() for c in fid.read(nc*4).split()]
ValueError: read length must be non-negative or -1

Process finished with exit code 1

```
Some questions about the input parameter:
- model_file/grid_file: There are two binary data files in one data package: h_EC2010 and UV_2010. Should I use one of them as model_file? Or using the Moudel_EC file which is the path info of those two files.

- EPSG : Which EPSG should I use for OTIS format tidal solutions.

- ilon/ilat: Should be str or float? Or should I write an array of longitudes and latitudes in a file?

I know those questions are basic and maybe a waste of your time to answer it, but they did trouble me a couple of days. If you can give answers or provide a complete example code to show me how to use it, will be appreciated! Thanks in advance!

**Comment by tsutterley** [comment]
Hi @tonystevenj!
Glad you found these programs potentially useful!  I haven't used any of the OTIS regional models so these are great questions.  

- The model file here is either `h_EC2010` (for tidal elevations: `TYPE='z'`) or `UV_EC2010` (for tidal zonal and meridional currents: `TYPE='u'` or `TYPE='v'`).  The `Model_EC` file that came with the tide model is the run file for the fortran and matlab equivalent tide programs ([OTPS](https://www.tpxo.net/otps) and [TMD](https://www.esr.org/research/polar-tide-models/tmd-software/)).  I chose to import the data a little differently when making these programs so that I could add more models (GOT and FES).
- These regional models are in EPSG `4326` (EC is at 2' resolution) :heavy_check_mark:
- Latitude and longitude can be entered as floats ([updated the programs today](https://github.com/tsutterley/pyTMD/pull/27) so that the coordinates don't have to be arrays.  The updated programs are presently being checked with [GitHub actions](https://github.com/tsutterley/pyTMD/actions/runs/271289359)). 

Unfortunately it looks like your point is on land (so the tidal values are invalid).  I am including some blurbs for checking your points.

Let me know how it goes and I'm happy to help in whatever way I can.

#### create a test plot to check if data is over valid points
```
import numpy as np
import pyTMD.convert_ll_xy
import pyTMD.read_tide_model
import matplotlib.pyplot as plt

grid_file = "F:/Z-Main Affairs(USA)/US Stusy/PyTMD/historical data/EC/DATA/grid_EC"
EPSG = '4326'
ilon = -73.935242
ilat = 40.730610

# if reading a single OTIS solution
xi,yi,hz,mz,iob,dt = pyTMD.read_tide_model.read_tide_grid(grid_file)

# adjust dimensions of input coordinates to be iterable
# run wrapper function to convert coordinate systems of input lat/lon
x,y = pyTMD.convert_ll_xy(np.atleast_1d(ilon),np.atleast_1d(ilat),EPSG,'F')

# adjust longitudinal convention of input latitude and longitude
# to fit tide model convention
if (np.min(x) < np.min(xi)) & (EPSG == '4326'):
    lt0, = np.nonzero(x < 0)
    x[lt0] += 360.0

if (np.max(x) > np.max(xi)) & (EPSG == '4326'):
    gt180, = np.nonzero(x > 180)
    x[gt180] -= 360.0

# check coordinates
plt.imshow(mz, interpolation='nearest', origin='lower',
    extent=(xi.min(),xi.max(),yi.min(),yi.max()))
plt.plot(x,y,'r*')
plt.show()
```

#### run tide time series program
```
import numpy as np
import pyTMD.time
import pyTMD.convert_ll_xy
import pyTMD.read_tide_model
import pyTMD.predict_tidal_ts
import pyTMD.infer_minor_corrections
import matplotlib.pyplot as plt

# EC grid and model file
grid_file = "F:/Z-Main Affairs(USA)/US Stusy/PyTMD/historical data/EC/DATA/grid_EC"
model_file = "F:/Z-Main Affairs(USA)/US Stusy/PyTMD/historical data/EC/DATA/h_EC2010"
EPSG = '4326'
ilon = -73.935242
ilat = 40.730610
# compute a time series for a day (60 second resolution)
itime = 60.0*np.arange(1440)
# convert time from units to days since 1992-01-01T00:00:00
tide_time = pyTMD.time.convert_delta_time(itime,
    epoch1=(2020,1,1,0,0,0), epoch2=(1992,1,1,0,0,0), scale=1.0/86400.0)
n_time = len(tide_time)

# read tidal constants and interpolate to grid points
amp,ph,D,c = pyTMD.read_tide_model.extract_tidal_constants(ilon, ilat, grid_file, model_file,
    EPSG, TYPE=type, METHOD='spline', GRID='OTPS')
deltat = np.zeros((n_time))
# calculate complex phase in radians for Euler's
cph = -1j*ph*np.pi/180.0
# calculate constituent oscillation
hc = amp*np.exp(cph)
# predict tide heights at times
tide = pyTMD.predict_tidal_ts(tide_time, hc, c, DELTAT=deltat, CORRECTIONS='OTIS')
tide += pyTMD.infer_minor_corrections(tide_time, hc, c, DELTAT=deltat, CORRECTIONS='OTIS')

# create a time series plot
plt.plot(tide_time, tide, 'r')
plt.xlabel('Days since 1992-01-01')
plt.ylabel('Tide Height [m]')
plt.title('EC')
plt.show()
```

**Comment by tonystevenj** [comment]
Thank you so much, you are so kind and those really help me a lot! Those days were busy on my course work. Sorry for the late reply.
