### ISSUE TITLE
Unable to run "extract_netcdf_constants" [Windows 10 OS]

### ISSUE THREAD

**Issue by kadir-orhan** [tsutterley/pyTMD#58]
I am unable to successfully run the function "extract_netcdf_constants.py" to read the data from uncompressed netCDF files.

The related part of my code is as follows:

_import pyTMD as tmd

grd_mod = 'c:\\Users\\user01\\Scripts_Python\\TPXO9_atlas_nc\\grid_tpxo9_atlas_v4.nc'
mod_M2_ = 'c:\\Users\\user01\\Scripts_Python\\TPXO9_atlas_nc\\h_m2_tpxo9_atlas_30_v4.nc'

amp, ph, D, c = tmd.extract_netcdf_constants(XX, YY, grd_mod, mod_M2_, GZIP=False)_

When I run the code, I receive the following error message:

_Traceback (most recent call last):
  File "hycom2bnd.py", line 233, in <module>
    amp,ph,D,ccc = tmd.extract_netcdf_constants(bndA_X[0],bndA_Y[0],grd_mod,mod_M2_,GZIP=False)
  File "C:\Users\user01\anaconda3\lib\site-packages\pyTMD\read_netcdf_model.py", line 189, in extract_netcdf_constants
    z,con = read_elevation_file(model_file, GZIP=GZIP)
  File "C:\Users\user01\anaconda3\lib\site-packages\pyTMD\read_netcdf_model.py", line 432, in read_elevation_file
    fileID = netCDF4.Dataset(os.path.expanduser(input_file),'r')
  File "netCDF4\_netCDF4.pyx", line 2321, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4\_netCDF4.pyx", line 1885, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'c'_

I use the latest anaconda installation with all the packages further upgraded and the python version is 3.8.

It seems like such a straightforward piece of code but at this point, I have no idea what is wrong and couldn't manage to fix the problem. I'd be glad if you can help me with the issue.

**Comment by tommy307507** [comment]
The issue here is python's escape character \ turning \U into a special character like \n , 
try putting r in front of the paths i.e. r'c:\Users\user01\Scripts_Python\TPXO9_atlas_nc\h_m2_tpxo9_atlas_30_v4.nc'

**Comment by tsutterley** [comment]
Hi @kadir-orhan, great question.  I agree with @tommy307507 that it looks like a path issue with windows.  I work on Linux machines so I am never quite sure if I've worked out all the kinks with PCs.

Using the `r` prefix should help by telling python to use the path string "as is".  Let me know if that works.  If not we'll figure it out!

**Comment by kadir-orhan** [comment]
I have tried using the r prefix, but it didn't make a difference. I have also tried to eliminate the path problem and change the current working directory to where the input files are stored, and provided the function with just the file names. Unfortunately, path or no path, the function doesn't read after the first character of the string input showing the grid or the model file. I still get the same error message. When the path is involved, it can't find "c" and when there is only the file name as input (e.g. h_m2_tpxo9_atlas_30_v4.nc), it can't find "h".

But I'm still relieved that this seems to be a problem with providing the input parameter in a proper way and not something deeper. Please let me know if you think I can try something else, or if you have a solution in mind. Meanwhile, I'll also check the code of the function. Thanks for the help!

**Comment by tommy307507** [comment]
After reading the source code it is because model file is treated as a list, the easy get around is to pass in a single element list
That's why it was looking for h as it can iterate thu the string like a list

**Comment by tommy307507** [comment]
Although it is listed in the documents, it would be helpful and good practice to do some type checking and error handling in the future. As types in python can be confusing like in this case.

**Comment by kadir-orhan** [comment]
This indeed seems to be the case. I have converted the model file input into a list and now the function runs without a problem. Thank you very much for your help.

**Comment by tsutterley** [comment]
Sorry @kadir-orhan that's right, the program is looking for a list of files.  For the netcdf TPXO9-atlas models each constituent comes in a single file.  I wrote the netcdf reader to parallel the "single file binary" reader so that it iterates to read all of the constituents inside the program.  So the `model_files` argument is a list with every file to be read.

If you're looking to only read a single constituent, simply encapsulate the string in some square brackets.  If you are looking to read all of the files from Svetlana then you can put them in that list and you'll be good to go!  I only have the binary v4 files so sorry about all the "higher order" programs looking for those.  I'll think about some way to parameterize those so the v2-v4 models could be either the netcdf or the binary and it'll go to the appropriate reader.

@tommy307507 is right in that there should be something to help you here in the reader.  I will add a catch that will exit with an exception detailing the problem.
